# Generated by Django 5.2.9 on 2026-01-06 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema_booking', '0001_initial'),
        ('managecinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableslots',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managecinema.cinemaarrangeslot'),
        ),
    ]
