# Generated by Django 5.2.9 on 2026-01-06 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema_booking', '0002_initial'),
        ('managecinema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookseat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seat',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managecinema.cinemadeck'),
        ),
        migrations.AddField(
            model_name='bookseat',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema_booking.seat'),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_manager', to='cinema_booking.seatmanager'),
        ),
    ]
